### PR TITLE
Fix finished condition and idle state

### PR DESCRIPTION
**Pull request by Caio-Batista**

### CODE REVIEW

**Comment by thiagomanel** [comment]
@Caio-Batista neat! two things:

1. remove all blank lines
2. did you test it? (I want to be sure the code between lines 40-61 is ok. note that, we do not need the catalog running to test it)

**Comment by Caio-Batista** [comment]
1. **All** blank lines? 
2. I tested all scenarios, just changing the input files, beyond that I checked every file from the query in database. Seams right.

**Comment by Caio-Batista** [comment]
1. Done

**Comment by thiagomanel** [comment]
@Caio-Batista all unnecessary blank line you added

**Comment by Caio-Batista** [comment]
@thiagomanel any further questions regarding this?  Can be merged already?

**Comment by thiagomanel** [comment]
nope. i will merge it

**Pull request merged**
